// Code generated by "github.com/zzztttkkk/lion/enums", DO NOT EDIT
package enums_test

import "fmt"

func (ev X) String() string {
	switch(ev){
		
		case X1 : {
			return "1"
		}
		
		case X2 : {
			return "2"
		}
		
		case X3 : {
			return "3"
		}
		
		case X4 : {
			return "4"
		}
		
		case X6 : {
			return "Six"
		}
		
		default: {
			panic(fmt.Errorf("enums_test.X: unknown enum value, %d", ev))
		} 
	}
}



func init(){
	
	AllXValues = append(AllXValues, X1)
	
	AllXValues = append(AllXValues, X2)
	
	AllXValues = append(AllXValues, X3)
	
	AllXValues = append(AllXValues, X4)
	
	AllXValues = append(AllXValues, X6)
	
}

