// Code generated by "stringer -type XInt -trimprefix X"; DO NOT EDIT.

package enums

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[XOne-0]
	_ = x[XTwo-1]
	_ = x[XThree-2]
}

const _XInt_name = "OneTwoThree"

var _XInt_index = [...]uint8{0, 3, 6, 11}

func (i XInt) String() string {
	if i < 0 || i >= XInt(len(_XInt_index)-1) {
		return "XInt(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _XInt_name[_XInt_index[i]:_XInt_index[i+1]]
}
